language: minimal

services:
  - docker

script:
  docker-compose -f docker-compose.test.yml build &&
  docker-compose -f docker-compose.test.yml up -d &&
  docker-compose -f docker-compose.test.yml run app make test-unit &&
  docker-compose -f docker-compose.test.yml run -e DB_HOST=ethereum-server-db -e DB_USER=postgres -e DB_NAME=postgres -e DB_PORT=5432 -e DB_SSL_MODE=disable -e ETH_RPC_ENDPOINT=node1:8501 app make test-integration

