language: minimal

services:
  - docker

env:
    matrix:
      - TARGET="docker-static-test"
      - TARGET="docker-middleware-test"
      - TARGET="docker-ethereum-test"
      - TARGET="docker-authentication-test"
      - TARGET="docker-api-gateway-test"

script:
  - make $TARGET
