version: '3'

services:
  app:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment: 
      - DB_HOST:ethereum-server-db
      - DB_USER:postgres
      - DB_NAME:postgres
      - DB_PORT:5432
      - DB_SSL_MODE:disable
      - ETH_RPC_ENDPOINT:node1:8501
  blockchain-bootnode:
    build:
      context: poa-ethereum
      dockerfile: bootnode.Dockerfile
  node1:
    build:
      context: poa-ethereum
      dockerfile: node1.Dockerfile
  node2:
    build:
      context: poa-ethereum
      dockerfile: node2.Dockerfile
  ethereum-server-db:
    image: postgres:latest
