openapi: 3.0.0
info:
  description: An implementation of a SEP compliant Stellar Anchor
  title: Stellar Test Anchor
  version: 1.0.0
servers:
- url: /
paths:
  /v1/authorizations:
    get:
      description: Requests a challenge transaction for the client to sign. Once signed,
        the challenge transaction is to be resubmitted back to the api.
      operationId: requestAChallenge
      parameters:
      - explode: true
        in: query
        name: account
        required: true
        schema:
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengeTransaction'
          description: Challenge Transaction
          links:
            resubmit:
              $ref: '#/components/links/ChallengeTransactionResubmit'
      summary: Request A Challenge
      tags:
      - Authorization
    post:
      description: Authenticates the user with a signed JWT token
      operationId: authenticate
      parameters:
      - explode: true
        in: query
        name: account
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChallengeTransaction'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: JWT Authentication Token
      summary: Authenticate A Challenge
      tags:
      - Authorization
  /v1/deposit:
    get:
      description: Gets the details for depositing currency into an account
      operationId: deposit
      parameters:
      - explode: true
        in: query
        name: account
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: asset_code
        required: true
        schema:
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDepositDetails'
          description: The deposit details
      security:
      - bearerAuth: []
      summary: Get Account Deposit Details
      tags:
      - Account
components:
  links:
    ChallengeTransactionResubmit:
      operationId: authenticate
      parameters:
        transaction: $response.body#/transaction
  schemas:
    AccountDepositDetails:
      example:
        how: 0x2C4c80B97de52AD03f1759cCC41747C76934ee3D
      properties:
        how:
          example: 0x2C4c80B97de52AD03f1759cCC41747C76934ee3D
          type: string
      type: object
    ChallengeTransaction:
      example:
        transaction: AAAAAP3z5PruosqouovJ83RCC6WM1tYr8e4hZHHFC1CDBcXKAAAAZAAAAAAAAAAAAAAAAQAAAABdMUqUAAAAAF0xS8AAAAAAAAAAAQAAAAEAAAAAdV2iRRpbBLR3/Xjf+xxG0JLMVClrKtmUox/sjbp7bbsAAAAKAAAAFlN0ZWxsYXIgRkkgQW5jaG9yIGF1dGgAAAAAAAEAAABAYXk2WEE3LVRYejJiTFFQZEYyT05raXRRZ2RfNEZ0dk1aS2Zwc1BLd1pyZU96LUwwNHZkSk5OLURBU2pFZWx5MAAAAAAAAAABgwXFygAAAEDU15m0XSyjln1uObo+MPu5gFwZOVg+dm1iS89KPYNckzK9O//5rJqEDl2u8YRKKRrcNaVnnxF5iJWKLnQA8mcP
      properties:
        transaction:
          example: AAAAAP3z5PruosqouovJ83RCC6WM1tYr8e4hZHHFC1CDBcXKAAAAZAAAAAAAAAAAAAAAAQAAAABdMUqUAAAAAF0xS8AAAAAAAAAAAQAAAAEAAAAAdV2iRRpbBLR3/Xjf+xxG0JLMVClrKtmUox/sjbp7bbsAAAAKAAAAFlN0ZWxsYXIgRkkgQW5jaG9yIGF1dGgAAAAAAAEAAABAYXk2WEE3LVRYejJiTFFQZEYyT05raXRRZ2RfNEZ0dk1aS2Zwc1BLd1pyZU96LUwwNHZkSk5OLURBU2pFZWx5MAAAAAAAAAABgwXFygAAAEDU15m0XSyjln1uObo+MPu5gFwZOVg+dm1iS89KPYNckzK9O//5rJqEDl2u8YRKKRrcNaVnnxF5iJWKLnQA8mcP
          type: string
      required:
      - transaction
      type: object
    AuthToken:
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjM1OTc5NzYsImlhdCI6MTU2MzUxMTU3NiwiaXNzIjoiIiwianRpIjoiMmNhZDNiMWE1Yjk3MzllYzZiYzI5M2Y4ZTJiNjFiYmU3NjRhY2RkOTBlMTQ1MTQ1MGI2Nzg2OGIxNDIwYmNmMCIsInN1YiI6IkdCMlYzSVNGREpOUUpORFg3VjRONzZZNEkzSUpGVENVRkZWU1ZXTVVVTVA2WkROMlBOVzNXWjY0In0.TOgt5WkwNFrx0wZU23kA11to59pxhFR8V6mB22mUI5I
      properties:
        token:
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjM1OTc5NzYsImlhdCI6MTU2MzUxMTU3NiwiaXNzIjoiIiwianRpIjoiMmNhZDNiMWE1Yjk3MzllYzZiYzI5M2Y4ZTJiNjFiYmU3NjRhY2RkOTBlMTQ1MTQ1MGI2Nzg2OGIxNDIwYmNmMCIsInN1YiI6IkdCMlYzSVNGREpOUUpORFg3VjRONzZZNEkzSUpGVENVRkZWU1ZXTVVVTVA2WkROMlBOVzNXWjY0In0.TOgt5WkwNFrx0wZU23kA11to59pxhFR8V6mB22mUI5I
          type: string
      required:
      - token
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
